name: PR
on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/test.yaml
